ippisite/ippidb/urls.py
"""
iPPI-DB URLs routing module
"""

from django.urls import include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import Sitemap
from django.urls import path
from django.urls import reverse
from rest_framework import routers
from . import views


ROUTER = routers.DefaultRouter()
ROUTER.register(r"pdb", views.PdbViewSet, basename="pdb")
ROUTER.register(r"distance", views.DistanceViewSet, basename="distance")
ROUTER.register(r"protein", views.ProteinViewSet, basename="protein")
ROUTER.register(r"chain", views.ChainViewSet, basename="chain")
ROUTER.register(r"hotspot", views.HotSpotViewSet, basename="hotspot")
ROUTER.register(r"ligand", views.LigandViewSet, basename="ligand")
ROUTER.register(r"partner", views.PartnerViewSet, basename="partner")
ROUTER.register(r"interactfile", views.InteractFileViewSet, basename="interactfile")
ROUTER.register(r"cavity", views.CavityViewSet, basename="cavity")
ROUTER.register(r"job", views.JobViewSet, basename="job")
ROUTER.register(r"linkedpdb", views.LinkedPDBViewSet, basename="linkedpdb")
ROUTER.register(r"summary", views.SummaryViewSet, basename="summary")


class IppiDbStaticSitemap(Sitemap):
    changefreq = "never"
    priority = 1

    def items(self):
        return [
            "index",
            "credits",
            "general",
            "pharmacology",
            "le_lle",
            "physicochemistry",
            "pca",
            "compound_list",
        ]

    def location(self, item):
        return reverse(item)

    def lastmod(self, obj):
        return None


sitemaps = {
    "static": IppiDbStaticSitemap,
    "compounds": views.IppiDbCompoundSitemap,
    "contributors": views.IppiDbContributorsSitemap,
}

urlpatterns = [
    re_path(r"^$", views.index, name="index"),
    re_path(r"^credits/$", views.credits, name="credits"),
    re_path(r"^citation/$", views.citation, name="citation"),
    re_path(r"^news/$", views.news, name="news"),
    re_path(r"^about-general/$", views.about_general, name="general"),
    re_path(r"^about-pharmacology/$", views.about_pharmacology, name="pharmacology"),
    re_path(r"^about-le-lle/$", views.about_le_lle, name="le_lle"),
    re_path(
        r"^about-physicochemistry/$",
        views.about_physicochemistry,
        name="physicochemistry",
    ),
    re_path(r"^about-pca/$", views.about_pca, name="pca"),
    re_path(
        r"^about-contributors/$",
        views.ContributorListView.as_view(),
        name="contributors",
    ),
    re_path(
        r"^about-contributors/(?P<pk>\d+)$",
        views.ContributorDetailView.as_view(),
        name="contributor_card",
    ),
    re_path(r"^targetcentric/$", views.PDBView.as_view(), name="cavities"),
    re_path(r"^targetcentric/summary$", views.SummaryView.as_view(), name="summary"),
    re_path(r"^targetcentric/tmaps$", views.pocketome_html, name="pocketome_html"),
    re_path(r"^targetcentric/networks$", views.NetworkView.as_view(), name="networks"),
    re_path(
        r"^cavity/(?P<pk>\d+)/near-cavities$",
        views.NearCavitiesHTMLFragmentView.as_view(),
        name="near_cavities",
    ),
    re_path(r"^api/", include(ROUTER.urls)),
    re_path(
        r"^api/builddistances$",
        views.build_distances,
        name="builddistances",
    ),
    re_path(r"^compounds/$", views.CompoundListView.as_view(), name="compound_list"),
    re_path(
        r"^compounds/IPPIDB-(?P<compound_id>\d+)$",
        views.CompoundCardBDCHEMRedirectView.as_view(),
        name="redirect_compound_card",
    ),
    re_path(
        r"^compounds/(?P<pk>\d+)$",
        views.CompoundDetailView.as_view(),
        name="compound_card",
    ),
    re_path(r"^tutorials$", views.tutorials, name="tutorials"),
    re_path(r"^contribute$", views.adminSession, name="admin-session"),
    re_path(
        r"^contribute/add/(?P<step>.+)/$", views.ippidb_wizard_view, name="ippidb_step"
    ),
    re_path(r"^contribute/add/$", views.ippidb_wizard_view, name="admin-session-add"),
    re_path(
        r"^contributions/(?P<pk>\d+)$",
        views.ContributionDetailView.as_view(),
        name="contribution-detail",
    ),
    re_path(r"^faq/$", views.FaqView.as_view(), name="faq"),
    re_path(r"^utils/mol2smi$", views.convert_mol2smi, name="mol2smi"),
    re_path(r"^utils/smi2mol$", views.convert_smi2mol, name="smi2mol"),
    re_path(r"^utils/smi2iupac$", views.convert_smi2iupac, name="smi2iupac"),
    re_path(r"^utils/iupac2smi$", views.convert_iupac2smi, name="iupac2smi"),
    re_path(r"^utils/getoutputjob$", views.get_output_job, name="getoutputjob"),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [re_path(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

ippisite/ippisite/urls.py
from django.urls import include, re_path
from django.contrib import admin
from . import views

urlpatterns = [
    re_path(r"^", include("ippidb.urls")),
    re_path(r"^settings/", include("live_settings.urls")),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^accounts/", include("allauth.urls")),
    re_path(r"^auth/", include("django.contrib.auth.urls")),
    re_path(r'^maintenance-mode/on/', views.maintenance_mode_on, name="maintenance_on"),
    re_path(r'^maintenance-mode/off/', views.maintenance_mode_off, name="maintenance_off"),
]

ippisite/ippidb/models/ippidb.py
"""
Models used in iPPI-DB
"""

from __future__ import unicode_literals

import operator
import re
import sys

from boltons.iterutils import flatten, unique_iter
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models, transaction
from django.db.models import FloatField, IntegerField, BooleanField
from django.db.models import Max, Count, F, Q, Case, When, Subquery, OuterRef, Exists
from django.db.models.functions import Cast
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from django_celery_results.models import TaskResult
from django.dispatch import receiver
from django.db.models.signals import post_save
from polymorphic.models import PolymorphicModel

from ippidb.utils import FingerPrinter, smi2inchi, smi2inchikey
from ippidb.ws import (
    get_pubmed_info,
    get_google_patent_info,
    get_uniprot_info,
    get_taxonomy_info,
    get_go_info,
    get_pfam_info,
    get_doi_info,
    get_chembl_id,
    get_pubchem_id,
    get_ligand_id,
    get_orcid_user_details,
    EntryNotFoundError,
)


class AutoFillableModel(models.Model):
    """
    AutoFillableModel abstract model to enable automated model fields
    filling from external sources in the autofill() method.
    The save method allows to either include autofill or not. in autofill kwarg
    is set to True, save() will first call autofill(), otherwise it won't
    """

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        auto_fill_needed = not self.is_autofill_done()
        if kwargs.get("autofill") is True or auto_fill_needed:
            auto_fill_needed = True
            self.autofill()
        if "autofill" in kwargs:
            del kwargs["autofill"]
        super(AutoFillableModel, self).save(*args, **kwargs)
        if auto_fill_needed:
            self.autofill_post_save()

    def autofill(self):
        raise NotImplementedError()

    def autofill_post_save(self):
        """
        Method called automatically after the save is done,
        usefull for setting m2m relations
        """
        pass

    def is_autofill_done(self):
        """
        test whether or not the model has been already autofilled
        """
        return True


class Bibliography(AutoFillableModel):
    """
    Bibliography reference
    (publications or patents)
    """

    SOURCES = (("PM", "PubMed ID"), ("PT", "Patent"), ("DO", "DOI"))
    id_source_validators = dict(
        PM=re.compile(r"^[0-9]+$"),
        PT=re.compile(r"^.*$"),
        DO=re.compile(r"^10.\d{4,9}/.+$"),
    )
    source = models.CharField(
        "Bibliographic type", max_length=2, choices=SOURCES, default=SOURCES[0][0]
    )
    id_source = models.TextField("Bibliographic ID")
    title = models.TextField("Title")
    journal_name = models.TextField("Journal name", null=True, blank=True)
    authors_list = models.TextField("Authors list")
    biblio_year = models.PositiveSmallIntegerField("Year")
    cytotox = models.BooleanField("Cytotoxicity data", default=False)
    in_silico = models.BooleanField("in silico study", default=False)
    in_vitro = models.BooleanField("in vitro study", default=False)
    in_vivo = models.BooleanField("in vivo study", default=False)
    in_cellulo = models.BooleanField("in cellulo study", default=False)
    pharmacokinetic = models.BooleanField("pharmacokinetic study", default=False)
    xray = models.BooleanField("X-Ray data", default=False)

    def autofill(self):
        """
        fetch information from external services
        (Pubmed or Google patents)
        """
        if self.source == "PM":
            info = get_pubmed_info(self.id_source)
        elif self.source == "PT":
            info = get_google_patent_info(self.id_source)
        elif self.source == "DO":
            info = get_doi_info(self.id_source)
        else:
            raise NotImplementedError()
        self.title = info["title"]
        self.journal_name = info["journal_name"]
        self.authors_list = info["authors_list"]
        self.biblio_year = info["biblio_year"]

    def is_autofill_done(self):
        return len(self.title) > 0

    def clean(self):
        super().clean()
        Bibliography.validate_source_id(self.id_source, self.source)

    def has_external_url(self):
        return self.source == "PM" or self.source == "DO"

    def get_external_url(self):
        """
        Get URL to the publication
        """
        if self.source == "PM":
            return f"https://www.ncbi.nlm.nih.gov/pubmed/{self.id_source}"
        elif self.source == "DO":
            return f"https://doi.org/{self.id_source}"
        elif self.source == "PT":
            return f"https://patentscope.wipo.int/search/en/detail.jsf?docId={self.id_source}"

    @staticmethod
    def validate_source_id(id_source, source):
        id_source_validator = Bibliography.id_source_validators[source]
        if not id_source_validator.match(id_source):
            raise ValidationError(
                dict(
                    id_source=_(
                        f"Must match pattern {id_source_validator.pattern}"
                        " for this selected source"
                    )
                )
            )
        return True

    class Meta:
        verbose_name_plural = "Bibliographies"
        verbose_name = "Bibliography"

    def data_and_study(self):
        ret = []
        for f in [
            "cytotox",
            "xray",
            "in_silico",
            "in_vitro",
            "in_cellulo",
            "in_vivo",
            "pharmacokinetic",
        ]:
            if getattr(self, f, False):
                ret.append(self._meta.get_field(f).verbose_name.title())
        return ", ".join(ret)

    def __str__(self):
        return "{}, {}".format(self.source, self.id_source)

    def get_absolute_url(self):
        return reverse("biblio-view", kwargs={"biblio_pk": self.pk})


class Taxonomy(AutoFillableModel):
    """
    Taxonomy IDs (from NCBI Taxonomy)
    and the corresponding human-readable name
    """

    taxonomy_id = models.DecimalField(
        "NCBI TaxID", unique=True, max_digits=9, decimal_places=0
    )
    name = models.CharField("Organism name", max_length=200)

    def autofill(self):
        """
        fetch information from external services
        (NCBI Entrez)
        """
        info = get_taxonomy_info(self.taxonomy_id)
        self.name = info["scientific_name"]

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "taxonomies"


class MolecularFunction(AutoFillableModel):
    """
    Molecular functions (from Gene Ontology)
    and the corresponding human-readable description
    """

    go_id = models.CharField("Gene Ontology ID", unique=True, max_length=10)
    # GO term id format: 'GO:0000000'
    description = models.CharField("description", max_length=500)

    def autofill(self):
        """
        fetch information from external services
        (EBI OLS)
        """
        info = get_go_info(self.go_id)
        self.description = info["label"]

    def is_autofill_done(self):
        return self.description is not None and len(self.description) > 0

    @property
    def name(self):
        return self.go_id + " " + self.description

    def __str__(self):
        return self.description


class Protein(AutoFillableModel):
    """
    Protein information (from Uniprot)
    and the corresponding human-readable name
    """

    uniprot_id = models.CharField("Uniprot ID", unique=True, max_length=10)
    recommended_name_long = models.TextField(
        "Uniprot Recommended Name (long)", blank=True, null=True
    )
    short_name = models.CharField("Short name", max_length=50)
    gene_name = models.CharField("Gene name", max_length=30, blank=True, null=True)
    entry_name = models.CharField("Entry name", max_length=30)
    organism = models.ForeignKey("Taxonomy", models.CASCADE)
    molecular_functions = models.ManyToManyField(MolecularFunction)
    domains = models.ManyToManyField("Domain")

    @transaction.atomic
    def autofill(self):
        """
        fetch information from external services
        (Uniprot) and create Taxonomy/Molecular Functions if needed
        """
        info = get_uniprot_info(self.uniprot_id)
        self.recommended_name_long = info["recommended_name"]

        gene_names = info["gene_names"]
        # put whatever name it find
        try:
            self.gene_name = gene_names[0]["name"]
        except IndexError:
            pass
        # then try to find the primary, if present
        for gene_name in gene_names:
            if gene_name["type"] == "primary":
                self.gene_name = gene_name["name"]
                break

        self.entry_name = info["entry_name"]
        self.short_name = info["short_name"]
        try:
            taxonomy = Taxonomy.objects.get(taxonomy_id=info["organism"])
        except Taxonomy.DoesNotExist:
            taxonomy = Taxonomy()
            taxonomy.taxonomy_id = info["organism"]
            taxonomy.save(autofill=True)
        self.organism = taxonomy
        self.__info = info

    def autofill_post_save(self):
        info = self.__info
        for go_id in info["molecular_functions"]:
            mol_function, created = MolecularFunction.objects.get_or_create(go_id=go_id)
            self.molecular_functions.add(mol_function)

        for domain_id in info["domains"]:
            domain, created = Domain.objects.get_or_create(pfam_acc=domain_id)
            self.domains.add(domain)

    def is_autofill_done(self):
        return len(self.entry_name) > 0

    def __str__(self):
        return "{} ({})".format(
            self.uniprot_id, self.recommended_name_long or self.short_name
        )


class Domain(AutoFillableModel):
    """

ippisite/ippidb/views/faq.py
from django.views.generic import ListView
from ippidb.models import Faq


class FaqView(ListView):
    """
    faq view
    """

    queryset = Faq.objects.all()
    model = Faq
    template_name = "FAQ.html"

ippisite/ippidb/views/site.py
from django.contrib.sitemaps import Sitemap
from ippidb.models import Compound, Contributor


class IppiDbCompoundSitemap(Sitemap):
    def items(self):
        return Compound.objects.validated()

    def lastmod(self, obj):
        return obj.get_last_modification_date()


class IppiDbContributorsSitemap(Sitemap):
    def items(self):
        return (
            Contributor.objects.all()
        )

    def lastmod(self, obj):
        return obj.get_last_modification_date()

ippisite/ippidb/views/tasks.py
from django.http import JsonResponse, HttpResponseBadRequest
from ippidb.models import Job


def get_output_job(request):
    """
    get a task information
    """

    task_id = request.GET.get("task_id")
    if task_id in [None, ""]:
        return HttpResponseBadRequest("task_id parameter is mandatory")
    try:
        job = Job.objects.get(task_result__task_id=task_id)
        resp = {
            "task_name": job.task_result.task_name,
            "task_id": job.task_result.task_id,
            "status": job.task_result.status,
            "create_time": job.task_result.date_created,
            "complete_time": job.task_result.date_done,
            "std_out": job.std_out,
            "std_err": job.std_err,
            "traceback": job.task_result.traceback,
        }
        return JsonResponse(resp)
    except Job.DoesNotExist:
        return HttpResponseBadRequest("task with id {} doesn't exist".format(task_id))

ippisite/ippidb/templates/ippidb/bibliography_card.html
{% load customtags %}
{%if object%}
<div class="{{css_class}}">
    <p class="contrib-card-title">{{object|verbose_name}}</p>
        {% if object.has_external_url %}
            <a class="float-left" target="_blank" href="{{ object.get_external_url }}">
        {% endif %}
        {{object.get_source_display}} - {{object.id_source}}
        {% if object.has_external_url %}
            </a><br/>
        {% endif %}
    <p> <span style="font-size: 18px;font-family: BrandonGrotesqueBld;">{{object.title }}</span><br />
        <i>{{ object.authors_list }}</i><br />
        {{object.journal_name }} ({{object.biblio_year}})<br /></p>
    <p><span style="font-family: BrandonGrotesqueBld;">Contains : </span>{{object.data_and_study}}</p>
</div>
{%endif%}

ippisite/ippidb/templates/ippidb/ppi_card.html
{% load customtags %}
{%if object%}
<div class="{{css_class}}">
    
    <p class="contrib-card-title" style="text-transform: uppercase;">{{object|verbose_name}} {{object.pdb_id}}</span>
    <table class="table table-sm table-striped">
        <tbody>
            <tr>
                <th><span style="font-family: BrandonGrotesqueBld;">{{object|verbose_name:'name'}}</span></th>
                <td>{{object.name }}</td>
            </tr>
            <tr>
                <th><span style="font-family: BrandonGrotesqueBld;">{{object|verbose_name:'family'}}</span></th>
                <td>{{object.family }}</td>
            </tr>
            <tr>
                <th><span style="font-family: BrandonGrotesqueBld;">{{object|verbose_name:'symmetry'}}</span></th>
                <td>{{object.symmetry }}</td>
            </tr>
            <tr>
                <th><span style="font-family: BrandonGrotesqueBld;">{{object|verbose_name:'pockets_nb'}}</span></th>
                <td>{{object.pockets_nb }}</td>
            </tr>
            <tr>
                <th><span style="font-family: BrandonGrotesqueBld;">{{object|verbose_name:'diseases'}}</span></th>
                <td>
                    {%for d in object.diseases.all %}
                    {{d}}{%if not forloop.last%},{%endif%}
                    {%endfor %}
                </td>
            </tr>
        </tbody>
    </table>
</div>
{%endif%}

ippisite/ippidb/templates/ippidb/refcompoundbiblio_table.html
{% load customtags %}
{%if objects and objects.exists%}
<table class="table vertical-align-middle" style="background-color: white; border: 1px solid #dee2e6;">
    <thead>
    {%with sample=objects.first%}
    <tr>
        <th>{{sample|verbose_name:'compound_name'}}</th>
        <th>{{sample.compound|verbose_name:'canonical_smile'}}</th>
        <th>{{sample.compound|verbose_name:'iupac_name'}}</th>
        <th>{{sample.compound|verbose_name:'ligand_id'}}</th>
        <th><i class="fa fa-link"></i>
    </tr>
    {%endwith%}
    </thead>
    <tbody>
    {%for o in objects%}
    <tr>
        <td>{{o.compound_name}}</td>
        <td>
            <canvas width="250" height="250" data-smiles="{{o.compound.canonical_smile}}"></canvas>
            {{o.compound.canonical_smile}}
        </td>
        <td>{{o.compound.iupac_name  | default_if_none:""}}</td>
        <td><a href="https://www.rcsb.org/ligand/{{ o.compound.ligand_id }}" target="_blank">{{ o.compound.ligand_id | default_if_none:""}}</a></td>
        <td>
            <a target="_blank" href="{% url 'compound_card' pk=o.compound.pk %}"><i class="fa fa-link"></i></a>
        </td>
    </tr>
    {%endfor%}
    </tbody>
</table>
{%endif%}

ippisite/ippidb/templates/ippidb/testactivitydescription_card.html
{% load customtags %}
{%if object%}
<div class="card mb-2 col-12">
    <h5 class="card-header">
        <span style="text-transform: capitalize;"> {{object|verbose_name}}</span> - <span style="text-transform: capitalize;">{{object.test_name}}</span>
    </h5>
    <div class="card-body row">
        <div class="col-6">
            <span style="font-family: BrandonGrotesqueBld;">{{object|verbose_name:'protein_domain_bound_complex'}}: </span>{{object.protein_domain_bound_complex}}
        </div>
        <div class="col-6">
            <span style="font-family: BrandonGrotesqueBld;">{{object|verbose_name:'is_primary'}}: </span>{{object.is_primary}}
        </div>
        <div class="col-6">
            <span style="font-family: BrandonGrotesqueBld;">{{object|verbose_name:'test_type'}}: </span>{{object.get_test_type_display}}
        </div>
        <div class="col-6">
            <span style="font-family: BrandonGrotesqueBld;">{{object|verbose_name:'test_modulation_type'}}: </span>{{object.get_test_modulation_type_display}}
        </div>
        <div class="col-6">
            <span style="font-family: BrandonGrotesqueBld;">{{object|verbose_name:'nb_active_compounds'}}: </span>{{object.nb_active_compounds}}
        </div>
        <div class="col-6">
            <span style="font-family: BrandonGrotesqueBld;">{{object|verbose_name:'cell_line'}}: </span>{{object.cell_line}}
        </div>
        <div class="col-12 mt-3">
            <table class="table">
                <tr>
                    <th>Compound</th>
                    <th>Modulation type</th>
                    <th>Activity type</th>
                    <th>Activity</th>
                </tr>
                {% for result in object.compoundactivityresult_set.all %}
                <tr>
                    <td>{{result.ref.compound_name}}</td>
                    <td>{{result.get_modulation_type_display}}</td>
                    <td title="{{result.get_activity_type_display}}">{{result.activity_type}}</td>
                    <td>{{result.activity|floatformat:2}}</td>
                </tr>
                {% endfor %}
            </table>  
        </div>
    </div>
    
</div>
{%endif%}

ippisite/ippidb/templates/ippidb/testcytotoxdescription_card.html
{% load customtags %}
{%if object%}
<div class="card mb-2 col-12">
    <h5 class="card-header">
        <span style="text-transform: capitalize;">{{object|verbose_name}}</span> - <span>{{object.test_name}}</span>
    </h5>
    <div class="card-body row">
        <div class="col-6">
            <span style="font-family: BrandonGrotesqueBld;">Compound concentration in μM: </span>{{object.compound_concentration}}
        </div>
        <div class="col-6">
            <span style="font-family: BrandonGrotesqueBld;">{{object|verbose_name:'cell_line'}}: </span>{{object.cell_line}}
        </div>
        <div class="col-12 mt-3">
            <table class="table">
                <tr>
                    <th>Compound</th>
                    <th>Toxicity</th>
                </tr>
                {% for result in object.compoundcytotoxicityresult_set.all %}
                <tr>
                    <td>{{result.ref.compound_name}}</td>
                    <td>{{result.toxicity}}</td>
                </tr>
                {% endfor %}
            </table>        
        </div>
    </div>

</div>
{%endif%}

ippisite/ippidb/templates/ippidb/testpkdescription_card.html
{% load customtags %}
{%if object%}
<div class="card mb-2 col-12">
    <h5 class="card-header">
        <span style="text-transform: capitalize;">{{object|verbose_name}}</span> - <span>{{object.test_name}}</span>
    </h5>
    <div class="card-body row">
        <div class="col-6">
            <span style="font-family: BrandonGrotesqueBld;">{{object|verbose_name:'organism'}}:
            </span>{{object.organism}}
        </div>
        <div class="col-6">
            <span style="font-family: BrandonGrotesqueBld;">{{object|verbose_name:'administration_mode'}}:
            </span>{{object.get_administration_mode_display}}
        </div>
        <div class="col-6">
            <span style="font-family: BrandonGrotesqueBld;">{{object|verbose_name:'concentration'}}:
            </span>{{object.concentration}}
        </div>
        <div class="col-6">
            <span style="font-family: BrandonGrotesqueBld;">{{object|verbose_name:'dose'}}:
            </span>{{object.dose}}
        </div>
        <div class="col-6">
            <span style="font-family: BrandonGrotesqueBld;">{{object|verbose_name:'dose_interval'}}:
            </span>{{object.dose_interval}}
        </div>
        <div class="col-12 mt-3">
            <table class="table">
                <tr>
                {% with result=object.compoundpkresult_set.first %}
                    <th>Compound</th>
                    <th>{{result|verbose_name:'tolerated'}}</th>
                    <th>{{result|verbose_name:'t_demi'}}</th>
                    <th>{{result|verbose_name:'t_max'}}</th>
                    <th>{{result|verbose_name:'auc_av'}}</th>
                    <th>{{result|verbose_name:'clearance_av'}}</th>
                    <th>{{result|verbose_name:'c_max_av'}}</th>
                    <th>{{result|verbose_name:'voldistribution_av'}}</th>
                {% endwith %}
                </tr>
                {% for result in object.compoundpkresult_set.all %}
                <tr>
                    <td>{{result.ref.compound_name}}</td>
                    <td>{{result.tolerated}}</td>
                    <td>{{result.t_demi}}</td>
                    <td>{{result.t_max}}</td>
                    <td>{{result.auc_av}}</td>
                    <td>{{result.clearance_av}}</td>
                    <td>{{result.c_max_av}}</td>
                    <td>{{result.voldistribution_av}}</td>
                </tr>
                {% endfor %}
            </table>        
        </div>
    </div>

</div>
{%endif%}